streamlit:
  title: "System Solar Assistant ğŸŒ ğŸª ğŸŒ” "
  tab_title: "DEVnuvols bot"
  logo: "./app/images/logo_facil.png"
  page_icon: "./app/images/logoDevNuvols.png"
  avatar: "./app/images/LOGO100X100.png"
  assistant_intro_message: "Hola ğŸ‘‹, soy tu asistente de IA especializado en el sistema solar, Â¿en quÃ© puedo ayudarte?"
  about: "Esto es un bot de prueba, autor: Miguel Monllau"
upload:
  tab_title: "Upload doc"
  page_icon: "./app/images/logoDevNuvols.png"